application: YOUREALLYNEEDTOCUSTOMIZETHIS
version: 1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /update
  script: update.py
  login: admin

- url: /send-newsletter
  script: newsletter.py
  login: admin

- url: /abo/.*
  script: subscribe.py

- url: /feed
  script: feed.py

- url: /.*
  script: view.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?*\.EXAMPLE

